### ISSUE TITLE
fix typo in the blog card component

### ISSUE THREAD

**Issue by kaf-lamed-beyt** [gdsc-kwasu/blog#27]
There's a typo in the component. This block below, specifically.

https://github.com/gdsc-kwasu/blog/blob/321830c3f46251e4a19df979a50335487a54e762/src/components/PostCardLists.jsx#L34-L37

You'll need to change 'publised' to "Published", and that's all.

**Comment by funabab** [comment]
😶

**Comment by kaf-lamed-beyt** [comment]
I want lopam to work on it
